all: compile

path = -I /users/lca/documents/projets/libraries/Glm/glm
bin = ../bin/osx
pathlib = lib/osx

compile:
	clang++ -Wc++11-extensions -arch x86_64 -m32 -W -Wall -g -fPIC -shared -I src $(path) -o $(bin)/glm.so src/*.cpp
	clang++ -Wc++11-extensions -arch i386   -m32 -W -Wall -g -fPIC -shared -I src $(path) -o $(bin)/glm32.so src/*.cpp
	
clean:
	rm $(bin)/*.so