name = "lca"
default_targets = ["lovejs"]
build_directory = "_build"

love_files = [
    "./apps/*.lua",
    "./engine/*.lua",
    "./graphics/*.lua",
    "./lua/*.lua",
    "./main.lua",,
    "./conf.lua",
]
