name = "lca"
default_targets = ["lovejs"]
build_directory = "build"

love_files = [
    "./apps/*.*",
    "./engine/*.lua",
    "./graphics/*.lua",
    "./lib/*.lua",
    "./lua/*.lua",
    "./scene/*.lua",
    "./lua_collection/*.lua",
    "./maths/*.lua",
    "./res/fonts/*.*",
    "./res/images/*.*",
    "./main.lua",
    "./conf.lua",
]
