name = "lca"
default_targets = ["lovejs"]
build_directory = "build"

love_files = [
    "./apps/*.*",
    "./engine/*.lua",
    "./graphics/*.lua",
    "./lib/*.lua",
    "./lua/*.lua",
    "./lua_collection/*.lua",
    "./maths/*.lua",
    "./physics/*.lua",
    "./res/fonts/*.*",
    "./res/images/*.*",
    "./scene/*.lua",
    "./conf.lua",
    "./main.lua",
]

[lovejs]
memory = "2000000000"  # starting memory of the webpage (default is 20 MB)
