!include <make\win32.mak> 

path =

bin = ..\bin\win
pathlib = lib\win

all: link

compile:
	$(cc) $(cdebug) $(cflags) $(cvardll) /EHsc /MDd $(path) /Fd$(bin)\vc140.pdb /Fo$(bin)\ src\tools.cpp

link: compile
    $(link) $(ldebug) $(dlllflags) $(conlibdll) -out:$(bin)\tools.dll $(bin)\tools.obj

clean:
	del $(bin)\*.obj