!include <make\win32.mak> 

path = -I "C:\Users\LMILHAU\Documents\Mes Projets Persos\Libraries\glm"

bin = ..\bin\win
pathlib = lib\win

all: link

compile:
	$(cc) $(cdebug) $(cflags) $(cvardll) /EHsc /MDd $(path) /Fd$(bin)\vc140.pdb /Fo$(pathlib)\ src\*.cpp

link: compile
    $(link) $(ldebug) $(dlllflags) $(conlibdll) -out:$(bin)\glm.dll $(pathlib)\*.obj

clean:
	del $(bin)\*.obj